### ISSUE TITLE
The visit registration route in the cust app

### ISSUE THREAD

**Issue by flancer64** [Ranncow/porter-base#8]
* отдельный маршрут и форма для регистрации визита в клиентском приложении через PIN
* Фронт-код для генерации идентификационных данных профиля
* Web API сервис для регистрации нового визита
* Кнопка по очистке локальных данных на форме регистрации (сброс профиля)

**Comment by flancer64** [comment]
Это должен быть маршурт для регистрации визитов через PIN (see #12)

**Comment by flancer64** [comment]
Процесс регистрации визита сейчас выглядит так:

1. Форма создания разрешения в деске
![image](https://github.com/user-attachments/assets/2633db5e-540c-4b49-baf3-08845929b194)

2. Получение администратором PIN'а для регистрации:
![image](https://github.com/user-attachments/assets/abe309b2-5560-45f4-bfd4-43cd2aecd8ef)

3. Ввод PIN'а посетителем (маршрут: /visit/reg/pin):
![image](https://github.com/user-attachments/assets/8deb6e98-2ac5-4140-8868-fa101105ed56)

4. Получение данных по визиту:
![image](https://github.com/user-attachments/assets/58ed7363-81a3-47c5-a787-af4444b9b03a)

5. Успешная регистрация визита:
![image](https://github.com/user-attachments/assets/90e362e0-0b00-4452-97c0-bd133e04e4c2)

**Comment by flancer64** [comment]
Код выложен на пилота, можно пробовать.

**Comment by Ordenion** [comment]
Круто, а снизу получается начало юзер интерфейса?

**Comment by flancer64** [comment]
Да, на данный момент домашняя страница клиента выглядит так. На неё и идёт перенаправление посетителя после удачной регистрации.

**Comment by flancer64** [comment]
Все доступные маршруты клиентского приложения сейчас в навигаторе:
![image](https://github.com/user-attachments/assets/b890d8b6-b0f3-497a-a756-89e87ceb2f44)

Пока что нет никакой разницы между анонимным и аутентифицированным клиентами. Всем всё доступно.
